# Chat prompt
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={{google_generative_language_api_key}}
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "Erzähle mir einen Witz."
        }
      ]
    }
  ],
  "system_instruction": {
    "parts": [
      {
        "text": "Antworte nur auf Deutsch."
      }
    ]
  },
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    }
  ],
  "generationConfig": {
    "temperature": 0.7,
    "topK": 1,
    "topP": 1,
    "maxOutputTokens": 1200
  }
}

###

# Upload picture
POST https://generativelanguage.googleapis.com/upload/v1beta/files?key={{google_generative_language_api_key}}
Content-Type: image/jpeg

< ./example-image.jpg

###

# Vision prompt (edit fileUri below)
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={{google_generative_language_api_key}}
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "Was ist in diesem Bild zu sehen?"
        },
        {
          "fileData": {
            "mimeType": "image/jpeg",
            "fileUri": "https://generativelanguage.googleapis.com/v1beta/files/ihbunuo8sc77"
          }
        }
      ]
    }
  ],
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    }
  ],
  "generationConfig": {
    "temperature": 0.7,
    "topK": 1,
    "topP": 1,
    "maxOutputTokens": 1200
  }
}

###
# Above picture is taken from https://pixabay.com/de/photos/wolkenkratzer-geb%C3%A4ude-hafen-5838029/
