### DLC file
POST https://dcrypt.it/decrypt/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dlcfile"; filename="dlc.dlc"

< ./example-dlc.dlc
--WebAppBoundary--

